### ISSUE TITLE
ApplicationRoleManager

### ISSUE THREAD

**Issue by saYRam** [trailmax/IoCIdentitySample#1]
How you can implement ApplicationRoleManager?

I tried this 
    public class ApplicationRoleManager : RoleManager<IdentityRole>
    {
        public ApplicationRoleManager(IRoleStore<IdentityRole, string> roleStore)
            : base(roleStore) { }

```
    public static ApplicationRoleManager Create(
        IdentityFactoryOptions<ApplicationRoleManager> options,
        IOwinContext context)
    {
        var manager = new ApplicationRoleManager(
            new RoleStore<IdentityRole>(context.Get<ApplicationDbContext>()));
        return manager;
    }
}
```

and this 

```
    public ApplicationRoleManager(IRoleStore<IdentityRole, string> roleStore)
        : base(roleStore)
    {
    }

    public static ApplicationRoleManager Create(IdentityFactoryOptions<ApplicationRoleManager> options, IOwinContext context)
    {
        //var manager = new ApplicationRoleManager(new RoleStore<IdentityRole>(context.Get<ApplicationDbContext>()));
        //var manager = new ApplicationRoleManager(new RoleStore(new DbContext()) { DisposeContext = true });
        var manager = DependencyResolver.Current.GetService<ApplicationRoleManager>();
        return manager;
    }
}
```

and added 

container.RegisterType<ApplicationRoleManager>(); to UnityConfig
and this one 
app.CreatePerOwinContext(() => DependencyResolver.Current.GetService<ApplicationRoleManager>())
to Startup.Auth

Getting "Object not set to an instance of an object" error.

**Comment by mii9000** [comment]
Same question as above

**Comment by mii9000** [comment]
@saYRam Sample of `RoleManager` is provided here #2

**Comment by trailmax** [comment]
@Ibrahim-Islam Thanks for answering this.
